import { db } from "./db";
import { agencyProfiles } from "@shared/schema";

const seedAgencies = [
  {
    userId: "seed-agency-1",
    name: "Advokatfirman Lindberg & Partners",
    description: "A leading Swedish law firm specializing in corporate law and commercial disputes. With over 30 years of experience, we provide expert legal counsel to businesses across Scandinavia.",
    address: "Strandvagen 7A",
    city: "Stockholm",
    latitude: 59.3329,
    longitude: 18.0789,
    phone: "+46 8 123 4567",
    email: "info@lindberglaw.se",
    website: "https://www.lindberglaw.se",
    specialties: ["Corporate Law", "Contract Law", "Civil Litigation"],
    employeeCount: 45,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-2",
    name: "Nordstrom Legal AB",
    description: "Boutique law firm focused on employment law and labor disputes. We represent both employers and employees in complex workplace matters.",
    address: "Kungsgatan 15",
    city: "Gothenburg",
    latitude: 57.7089,
    longitude: 11.9746,
    phone: "+46 31 987 6543",
    email: "kontakt@nordstromlegal.se",
    website: "https://www.nordstromlegal.se",
    specialties: ["Employment Law", "Civil Litigation", "Contract Law"],
    employeeCount: 18,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-3",
    name: "Eriksson & Svensson Advokatbyra",
    description: "Full-service law firm with expertise in family law, estate planning, and real estate transactions. Serving clients in southern Sweden since 1995.",
    address: "Sodra Forstadsgatan 22",
    city: "Malmo",
    latitude: 55.5989,
    longitude: 13.0038,
    phone: "+46 40 456 7890",
    email: "info@erikssonlaw.se",
    website: "https://www.erikssonlaw.se",
    specialties: ["Family Law", "Real Estate", "Tax Law"],
    employeeCount: 25,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-4",
    name: "Westberg Juridik",
    description: "Criminal defense firm with a strong track record. Our experienced attorneys handle everything from minor offenses to complex financial crimes.",
    address: "Drottninggatan 30",
    city: "Stockholm",
    latitude: 59.3370,
    longitude: 18.0645,
    phone: "+46 8 234 5678",
    email: "info@westbergjuridik.se",
    website: "https://www.westbergjuridik.se",
    specialties: ["Criminal Law", "Civil Litigation"],
    employeeCount: 12,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-5",
    name: "Bergman IP Law",
    description: "Specialized intellectual property law firm. We help startups and established companies protect their innovations, trademarks, and creative works.",
    address: "Vasagatan 42",
    city: "Stockholm",
    latitude: 59.3318,
    longitude: 18.0558,
    phone: "+46 8 345 6789",
    email: "info@bergmanip.se",
    website: "https://www.bergmanip.se",
    specialties: ["Intellectual Property", "Corporate Law", "Contract Law"],
    employeeCount: 8,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-6",
    name: "Johansson & Olsson",
    description: "Immigration law experts helping individuals and families navigate Swedish immigration procedures. Multilingual team fluent in Swedish, English, and Arabic.",
    address: "Ostra Hamngatan 16",
    city: "Gothenburg",
    latitude: 57.7068,
    longitude: 11.9668,
    phone: "+46 31 567 8901",
    email: "info@jolaw.se",
    website: "https://www.jolaw.se",
    specialties: ["Immigration Law", "Family Law", "Civil Litigation"],
    employeeCount: 15,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-7",
    name: "Nilsson Tax & Legal",
    description: "Tax law specialists providing advisory services to businesses and high-net-worth individuals. Expertise in Swedish and international tax planning.",
    address: "Hamngatan 8",
    city: "Uppsala",
    latitude: 59.8586,
    longitude: 17.6389,
    phone: "+46 18 678 9012",
    email: "info@nilssontax.se",
    website: "https://www.nilssontax.se",
    specialties: ["Tax Law", "Corporate Law", "Bankruptcy"],
    employeeCount: 10,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-8",
    name: "Soderberg Maritime Law",
    description: "Leading maritime and shipping law firm in Scandinavia. We advise shipowners, charterers, and insurers on all aspects of maritime commercial law.",
    address: "Skeppsbron 2",
    city: "Stockholm",
    latitude: 59.3249,
    longitude: 18.0733,
    phone: "+46 8 456 7890",
    email: "info@soderbergmaritime.se",
    website: "https://www.soderbergmaritime.se",
    specialties: ["Maritime Law", "Insurance Law", "Contract Law"],
    employeeCount: 20,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-9",
    name: "Karlsson Environment Law",
    description: "Environmental law firm focused on sustainability, environmental compliance, and green energy projects. Helping companies navigate complex environmental regulations.",
    address: "Norrlandsgatan 12",
    city: "Lulea",
    latitude: 65.5843,
    longitude: 22.1567,
    phone: "+46 920 789 012",
    email: "info@karlssonenv.se",
    website: "https://www.karlssonenv.se",
    specialties: ["Environmental Law", "Corporate Law", "Real Estate"],
    employeeCount: 7,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-10",
    name: "Andersson & Berg Advokatbyra",
    description: "Personal injury specialists with a proven record of securing fair compensation for accident victims. No win, no fee policy on select cases.",
    address: "Stora Nygatan 5",
    city: "Malmo",
    latitude: 55.6036,
    longitude: 12.9997,
    phone: "+46 40 890 1234",
    email: "info@anderssonberg.se",
    website: "https://www.anderssonberg.se",
    specialties: ["Personal Injury", "Insurance Law", "Civil Litigation"],
    employeeCount: 14,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-11",
    name: "Pettersson Legal Group",
    description: "Multi-disciplinary law firm offering comprehensive legal services. Offices in Stockholm and Gothenburg serving clients throughout Sweden.",
    address: "Birger Jarlsgatan 20",
    city: "Stockholm",
    latitude: 59.3397,
    longitude: 18.0723,
    phone: "+46 8 567 8901",
    email: "info@petterssonlegal.se",
    website: "https://www.petterssonlegal.se",
    specialties: ["Corporate Law", "Employment Law", "Real Estate", "Tax Law"],
    employeeCount: 55,
    subscriptionActive: true,
  },
  {
    userId: "seed-agency-12",
    name: "Dahl Bankruptcy & Restructuring",
    description: "Specialists in corporate insolvency, debt restructuring, and bankruptcy proceedings. Helping businesses find solutions during financial difficulty.",
    address: "Luntmakargatan 18",
    city: "Stockholm",
    latitude: 59.3395,
    longitude: 18.0615,
    phone: "+46 8 678 9012",
    email: "info@dahllaw.se",
    website: "https://www.dahllaw.se",
    specialties: ["Bankruptcy", "Corporate Law", "Contract Law"],
    employeeCount: 9,
    subscriptionActive: true,
  },
];

async function seed() {
  console.log("Seeding agency profiles...");

  for (const agency of seedAgencies) {
    try {
      await db.insert(agencyProfiles).values(agency).onConflictDoNothing();
      console.log(`  Seeded: ${agency.name}`);
    } catch (error) {
      console.log(`  Skipped (already exists): ${agency.name}`);
    }
  }

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
